const checkDict = {
  1: "Didn't complete faction task (-15)",
  2: 'Failure condition happened (-25)',
  3: 'Wore your factions patch (+5)',
  4: 'Brought back usable tool (+5)',
  5: 'Found and used a piece of gear in the field (+5)',
  6: 'Brought and played harmonica or acoustic guitar (+5)',
  7: 'Brought and read hard copy of Roadside Picnic (+5)',
  8: 'It rained or snowed the entire time (+5)',
  9: 'Spent each night in a different structure (+10)',
  10: 'Lit a campfire in an old container and squatted around it (+10)',
  11: 'Stalked during winter and the average temperature was below freezing (+10)',
  12: 'Your entire party was the same faction (+5)',
  13: 'Left a stash behind (+5)',
  14: "Found another Stalker's stash (+10)",
  15: 'Explored a real-life exclusion zone (+20)',
  16: 'Zone was actually irradiated above normal ambient levels (+20)',
  17: 'Actually did this in Chernobyl (+40)',
  18: 'Brought pistol carbine or 9x18 pistol (+5)',
  19: 'Wore nothing but Adidas clothing (+5)',
  20: "Snuck up behind a non-stalker, shouted 'CHEEKI BREEKI IV DAMKE' and ran away (+15)",
  21: 'Slavshit rifle and pistol combo (+5)',
  22: 'Only ate MREs (+5)',
  23: 'Armor was actually slavshit (+10)',
  24: 'Audibly chanted or made noise while praying (+5)',
  25: 'Wore a gas mask at all times while outside (+10)',
  26: 'Wore gas mask or respirator at all times while inside a structure (+10)',
  27: 'Did logging with a Geiger counter (+5)',
  28: 'Did logging with a toxic gas meter (+10)',
  29: 'Brought two friends and designated one as the commander (+10)',
  30: 'Logged complete field report on paper, placed report in stash and posted photos of report to /k/ (+10)',
  31: 'Killed a mutant (any wild animal) (+5)',
  32: 'Posted or will post a complete field report of everything you did and observed on /k/ (+10)',
  33: 'Wore all Flecktarn camo (+5)',
  34: 'Smoked something (cigs, pot, random plant, etc) (+10)',
  35: 'Camped in a swamp (+5)',
  36: 'Set up a base with fortifications and/or camo netting or similar disguise (+5)',
  37: 'Set up a second base and camp in one of your two bases (+10)',
  38: 'It rained or snowed (+5)'
};

export default checkDict;
